--DROP IF DATABASE ALREADY EXISTS
DROP DATABASE IF EXISTS DataWarehouse;
--CREATE DATABASE
CREATE DATABASE DataWarehouse;

--CREATING 3 SEPARATE SCHEMA FOR SEPARATE LAYERS

CREATE SCHEMA IF NOT EXISTS  bronze;


CREATE SCHEMA IF NOT EXISTS silver;


CREATE SCHEMA IF NOT EXISTS gold;
